name: "CI"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: "Setup ROS"
        uses: ros-tooling/setup-ros@v0.5
        with:
          required-ros-distributions: noetic
      - name: "Build & Test"
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros1-distro: noetic
